
-- Seed additional press releases
INSERT INTO public.blog_posts (title, slug, excerpt, content, author_id, is_published, published_at, category, cover_image_url)
VALUES
('Shop4Me Partners with Leading Lagos Markets for Faster Shopping', 'shop4me-partners-lagos-markets', 'Strategic partnerships with Balogun, Computer Village, and Trade Fair markets streamline the shopping experience for thousands of customers.', 'Shop4Me has announced strategic partnerships with major Lagos markets including Balogun Market, Computer Village, and Trade Fair Complex. These partnerships enable our agents to navigate markets more efficiently, access better pricing for customers, and ensure faster order fulfillment. The initiative is part of our commitment to making market shopping accessible to everyone, regardless of their schedule or location. With dedicated agent stations now set up in these markets, average shopping times have been reduced by 40%.', '00000000-0000-0000-0000-000000000000', true, now() - interval '20 days', 'press', NULL),

('Shop4Me Reaches 10,000 Successful Deliveries Milestone', 'shop4me-10000-deliveries', 'A major milestone as Shop4Me completes 10,000 successful deliveries across Lagos and Port Harcourt, with a 98% customer satisfaction rate.', 'Shop4Me is proud to announce that we have successfully completed over 10,000 deliveries since our launch. This milestone reflects the trust our customers place in us and the dedication of our growing network of shopping agents. Our customer satisfaction rate stands at an impressive 98%, with an average delivery time of under 3 hours. We are grateful to every customer, agent, and team member who has contributed to this achievement. As we continue to grow, we remain committed to providing the best personal shopping and delivery service in Nigeria.', '00000000-0000-0000-0000-000000000000', true, now() - interval '15 days', 'press', NULL),

('Shop4Me Introduces Wallet Payment System for Seamless Transactions', 'shop4me-wallet-payment-system', 'New in-app wallet feature allows customers to fund their account and pay for orders instantly, eliminating payment delays.', 'Shop4Me has launched a new wallet payment system that allows customers to pre-fund their accounts and pay for shopping orders instantly. The wallet supports bank transfers, card payments via Paystack, and can be topped up at any time. This feature eliminates the friction of per-order payments and ensures agents can begin shopping immediately upon order acceptance. The wallet also provides detailed transaction history and spending summaries, giving customers full visibility into their shopping expenses.', '00000000-0000-0000-0000-000000000000', true, now() - interval '10 days', 'press', NULL),

('Shop4Me Expands Agent Network with New Training Program', 'shop4me-agent-training-program', 'A comprehensive training initiative equips new agents with market navigation skills, customer service excellence, and efficient delivery practices.', 'Shop4Me has launched an enhanced agent training program designed to maintain our high service standards as we scale. The program covers market navigation techniques, product quality assessment, customer communication best practices, and safe delivery protocols. New agents undergo a rigorous vetting process including background checks and market knowledge assessments before being approved. This investment in our agent network ensures every Shop4Me customer receives consistent, professional service regardless of which agent handles their order.', '00000000-0000-0000-0000-000000000000', true, now() - interval '5 days', 'press', NULL);

-- Seed blog posts
INSERT INTO public.blog_posts (title, slug, excerpt, content, author_id, is_published, published_at, category, cover_image_url)
VALUES
('5 Tips for Getting the Best Deals at Lagos Markets', 'tips-best-deals-lagos-markets', 'Our experienced agents share insider tips on how to get the best prices and quality products from Lagos popular markets.', 'Shopping at Lagos markets can be overwhelming, but our agents have mastered the art. Here are their top tips: 1) **Shop early** — The freshest produce and best selections are available before 10am. 2) **Know the market layout** — Each market has zones. Balogun is best for fabrics, Computer Village for electronics, and Mile 12 for foodstuffs. 3) **Compare prices** — Always check at least 3 stalls before buying. Prices can vary by 20-30%. 4) **Build relationships** — Regular sellers offer better prices to returning customers. Our agents have established relationships across major markets. 5) **Check quality carefully** — Especially for electronics and perishables, thorough inspection is essential. When you use Shop4Me, our agents apply all these principles to ensure you get the best value for your money.', '00000000-0000-0000-0000-000000000000', true, now() - interval '18 days', 'blog', NULL),

('How Shop4Me is Changing the Way Nigerians Shop', 'how-shop4me-changing-shopping', 'From busy professionals to new mothers, discover how Shop4Me is transforming everyday shopping for Nigerians across Lagos and Port Harcourt.', 'The traditional Nigerian shopping experience often involves navigating crowded markets, negotiating prices, and spending hours in traffic. Shop4Me is reimagining this experience by connecting customers with trusted shopping agents who handle everything from market navigation to doorstep delivery. Our platform serves diverse customers: busy professionals who cannot leave work, new parents juggling childcare, elderly individuals who find market trips challenging, and anyone who simply values their time. With real-time chat, live order tracking, and transparent pricing through our invoice system, customers maintain full control while our agents do the heavy lifting. The response has been overwhelming — customers report saving an average of 4 hours per shopping trip while often getting better prices through our experienced agents market knowledge.', '00000000-0000-0000-0000-000000000000', true, now() - interval '12 days', 'blog', NULL),

('A Day in the Life of a Shop4Me Agent', 'day-in-life-shop4me-agent', 'Follow one of our top-rated agents through a typical day of shopping, navigating markets, and delivering joy to customers across Lagos.', 'Meet Adebayo, one of Shop4Me''s top-rated agents with over 500 completed orders and a 4.9-star rating. His day starts at 7am, checking the app for new orders near his base in Surulere. By 8am, he has accepted three orders — two from Balogun Market and one from Computer Village. He plans his route to minimize travel time, starting with Computer Village before heading to Balogun. At each market, Adebayo uses his extensive network of trusted sellers to find the best products at fair prices. He sends photos and updates to customers via the in-app chat, confirming items before purchase. By 2pm, all three orders are shopped and invoiced. He begins deliveries, using the app''s navigation to reach each customer efficiently. By 5pm, all deliveries are complete with happy customers. Adebayo earns competitive fees for each delivery and takes pride in the 5-star reviews he consistently receives. For him, being a Shop4Me agent is more than a job — it is entrepreneurship with purpose.', '00000000-0000-0000-0000-000000000000', true, now() - interval '7 days', 'blog', NULL),

('Understanding Shop4Me Pricing: Complete Transparency', 'understanding-shop4me-pricing', 'A clear breakdown of how Shop4Me pricing works — from service fees to delivery charges — so you always know what you are paying for.', 'At Shop4Me, we believe in complete pricing transparency. Here is how our pricing works: **Item Costs** — You pay the exact market price for your items. Our agents send photos and prices for your approval before purchasing. **Service Fee** — A flat service fee covers agent compensation for shopping on your behalf. This fee is clearly displayed before you confirm your order. **Delivery Fee** — Based on distance from the market to your delivery address. You see this upfront when placing your order. **No Hidden Charges** — Every cost is itemized in your final invoice. You can review the complete breakdown in your order history. Our goal is to make the total cost comparable to what you would spend shopping yourself when you factor in transportation, time, and the convenience of doorstep delivery. Many customers find that Shop4Me actually saves them money through our agents skilled price negotiation.', '00000000-0000-0000-0000-000000000000', true, now() - interval '3 days', 'blog', NULL);
